# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zzw85\Desktop\proj\delay_key\pausepass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PausePass(object):
    def setupUi(self, PausePass):
        PausePass.setObjectName("PausePass")
        PausePass.resize(242, 184)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PausePass.sizePolicy().hasHeightForWidth())
        PausePass.setSizePolicy(sizePolicy)
        PausePass.setMinimumSize(QtCore.QSize(182, 184))
        self.pushButton = QtWidgets.QPushButton(PausePass)
        self.pushButton.setGeometry(QtCore.QRect(50, 20, 141, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(PausePass)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 100, 141, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(PausePass)
        QtCore.QMetaObject.connectSlotsByName(PausePass)

    def retranslateUi(self, PausePass):
        _translate = QtCore.QCoreApplication.translate
        PausePass.setWindowTitle(_translate("PausePass", "PausePass"))
        self.pushButton.setText(_translate("PausePass", "生成密码"))
        self.pushButton_2.setText(_translate("PausePass", "显示密码"))
